version: '3'
services:
  mysql:
        image: mysql:5.7
        container_name: mysqlCon
        command: --default-authentication-plugin=mysql_native_password

        volumes:
          - .:/ahp_survey
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=.root.
          - MYSQL_DATABASE=ahp_survey
          
        ports:
          - "8082:3306"
  website:
    container_name: php
    image: php:7.4-apache
    build:
      context: ./
    volumes:
      - /Innal/Proyek 3/New folder/ahp_survey/src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql